### ISSUE TITLE
Query to data containing the symbol ' results in faulty json

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oedialect#28]
@Ludee created a query for two structurally identical tables. It succeeds for one and fails for another. @coroa neatly narowed the problem down for us. The issue also concisely describes the problem

For reference: https://github.com/coroa/saio/issues/4

@MGlauer this is high priority for us. How quickly could a fix be implemented?

Just for good measure, I'm attaching the query files again here: [oep_mastr_query.zip](https://github.com/OpenEnergyPlatform/oedialect/files/4276146/oep_mastr_query.zip).

**Comment by jh-RLI** [comment]
The error occurs because quotes are not escapes. I would suggest to include something like this:
oedialect/engine.py change line 177 to
```python
try:
  yield json.loads(line.decode('utf8').replace("'", '"'))
except:
  yield json.loads(line.decode('utf8').replace("'", '\\"'))
```
@MGlauer are you ok with this? or would simply changing to `yield json.loads(line.decode('utf8').replace("'", '\\"')` without the exception be enough. I tested both and it worked just fine.
